databases:
  - name: a121_db
    databaseName: a121_db
    user: a121_user

services:
  - type: web
    name: a121_backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn a121_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: a121_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    autoDeploy: true
